### ISSUE TITLE
Admin_password

### ISSUE THREAD

**Issue by tigerduck42** [the-kbA-team/cakephp-graylog#1]
Hi,

just a suggestion, could you add "admin_password" to the password_keys.
https://github.com/the-kbA-team/cakephp-graylog/blob/master/src/Log/Engine/GraylogLog.php#L42

Kindest regards
Martin

**Comment by gregor-j** [comment]
@tigerduck42  This is configurable in your own settings. Just add `admin_password` to the `password_keys` array.

```php
<?php
\Cake\Core\Configure::write('Log.graylog', [
    'className' => \kbATeam\CakePhpGraylog\Log\Engine\GraylogLog::class,
    'host' => 'graylog.example.com',
    'password_keys' => ['admin_password']
]);
```

or for cake2:
```php
<?php
CakePlugin::load('Graylog');
CakeLog::config('graylog', [
    'engine' => 'Graylog.Graylog',
    'host' => 'graylog.example.com',
    'password_keys' => ['admin_password']
]);
```

**Comment by tigerduck42** [comment]
@gregor-j Thanks, I found it by myself. :-)
