### ISSUE TITLE
Support CakePhp 4

### ISSUE THREAD

**Issue by aaronbach** [the-kbA-team/cakephp-graylog#5]
Thanks for your work. I'm looking for exactly the functionality you are providing.
I'm using CakePhp 4. The library is officially supporting CakePhp ~3 (composer.json).

Are there any known Reasons, why not bump the compatibility in the composer.json to also support cakephp version 4?

Thanks

**Comment by gregor-j** [comment]
I bumped the version and created a release (3.0). The tests are passing, but I currently have no cake4 projects and I don't know if it actually works in a cake4 environment.

**Comment by zelmandesign** [comment]
Thanks for Your work on this package. Can You also make it compatible with CakePHP 4.0?
