### ISSUE TITLE
NetworkException when GrayLogServer down

### ISSUE THREAD

**Issue by aaronbach** [the-kbA-team/cakephp-graylog#6]
We are having troubles, when our GraylogServer is not reachable. We are getting an NetworkException and our Application is down.

We have configured UDP.

Is there a way to catch the Exception and ignore Downtimes of the GraylogServer.

Thanks

**Comment by gregor-j** [comment]
solved in releases 1.3.0 (cake2) and 2.3.0 (cake3)
